<?php
/**
 * Created by PhpStorm.
 * User: thangnguyen
 * Date: 21/11/2018
 * Time: 17:35
 */

namespace QHO\Staff\Block\Adminhtml\Staff\Edit;

use Magento\Backend\Block\Widget\Form\Generic;
use QHO\Staff\Model\Config\Status;

class Form extends Generic
{
    protected $_staffStatus;

    /**
     * Form constructor.
     * @param \Magento\Backend\Block\Template\Context $context
     * @param \Magento\Framework\Registry $registry
     * @param \Magento\Framework\Data\FormFactory $formFactory
     * @param array $data
     */
    public function __construct(\Magento\Backend\Block\Template\Context $context,
                                \Magento\Framework\Registry $registry,
                                \Magento\Framework\Data\FormFactory $formFactory,
                                Status $status,
                                array $data = [])
    {
        $this->_staffStatus = $status;
        parent::__construct($context, $registry, $formFactory, $data);
    }

    /**
     *Construct
     */
    protected function _construct()
    {
        $this->setId("staff_form");
        $this->setTitle(__("Staff Information"));
        parent::_construct(); // TODO: Change the autogenerated stub
    }

    /**
     * @return Generic
     */
    protected function _prepareForm()
    {
        $model = $this->_coreRegistry->registry("staff");
        $form = $this->_formFactory->create(
            [
                "data" => [
                    "id" => "edit_form",
                    "action" => $this->getData("actions"),
                    "method" => "post",
                    "enctype" => "multipart/form-data",
                ]
            ]
        );
        $fieldset = $form->addFieldset(
            "base_fieldset",
            [
                "legend" => __("General Information"), "class" => "fieldset-wide"
            ]
        );
        if($model->getId()){
            $fieldset->addField(
                "id",
                "hidden",
                [
                    "name"=>"id"
                ]
            );
        }
        $fieldset->addField(
            "name",
            "text",
            [
                "name" => "name",
                "label" => __("Full Name"),
                "required" => true,
            ]
        );
        $fieldset->addField(
            "email",
            "text",
            [
                "name" => "email",
                "label" => __("Email"),
                "required" => true,
            ]
        );
        $fieldset->addField(
            "phone",
            "text",
            [
                "name" => "phone",
                "label" => __("Phone"),
                "required" => true,
            ]
        );
        $fieldset->addField(
            "position",
            "text",
            [
                "name" => "position",
                "label" => __("Position"),
                "required" => true,
            ]
        );
        $fieldset->addField(
            "status",
            "select",
            [
                "name" => "status",
                "label" => __("Status"),
                "required" => true,
                "options" => $this->_staffStatus->toOptionArray()
            ]
        );
        $fieldset->addField(
            "avatar",
            "image",
            [
                "name" => "avatar",
                "label" => __("Avatar"),
                "required" => true,
            ]
        );
        $data = $model->getData();
        $form->setValues($data);
        $form->setHtmlIdPrefix("staff_main_");
        $form->setUseContainer(true);
        $this->setForm($form);
        return parent::_prepareForm(); // TODO: Change the autogenerated stub
    }
}