<?php
/**
 * Created by PhpStorm.
 * User: thangnguyen
 * Date: 30/10/2018
 * Time: 18:23
 */
namespace Smart\Hello\Controller\Test;

use Magento\Framework\App\Action\Context;
use Magento\Framework\App\RequestInterface;

class Save extends \QHO\Hello\Controller\Index\Index{
    public function __construct(Context $context, RequestInterface $request)
    {
        parent::__construct($context, $request);
    }

    public function execute()
    {
        parent::execute(); // TODO: Change the autogenerated stub
    }
}