<?php
/**
 * Created by PhpStorm.
 * User: thangnguyen
 * Date: 21/11/2018
 * Time: 17:33
 */

namespace QHO\Staff\Block\Adminhtml\Staff;

use Magento\Backend\Block\Widget\Form\Container;

class Edit extends Container
{
    /**
     * Construct
     */
    protected function _construct()
    {
        $this->_blockGroup = "QHO_Staff";
        $this->_controller = "adminhtml_staff";
        $this->_objectId = "id";
        parent::_construct(); // TODO: Change the autogenerated stub
    }
}