<?php
/**
 * Created by PhpStorm.
 * User: thangnguyen
 * Date: 09/11/2018
 * Time: 16:00
 */
namespace QHO\Schema\Model\ResourceModel\DataExample;

class Collection extends \Magento\Framework\Model\ResourceModel\Db\Collection\AbstractCollection{
    public function _construct()
    {
        $this->_init("QHO\Schema\Model\DataExample", "QHO\Schema\Model\ResourceModel\DataExample");
        parent::_construct(); // TODO: Change the autogenerated stub
    }
}