<?php
/**
 * Created by PhpStorm.
 * User: thangnguyen
 * Date: 19/11/2018
 * Time: 15:31
 */

namespace QHO\Staff\Model\ResourceModel\Staff;
class Collection extends \Magento\Framework\Model\ResourceModel\Db\Collection\AbstractCollection
{
    protected function _construct()
    {
        $this->_init("QHO\Staff\Model\Staff", "QHO\Staff\Model\ResourceModel\Staff");
        parent::_construct(); // TODO: Change the autogenerated stub
    }
}