<?php
/**
 * Created by PhpStorm.
 * User: thangnguyen
 * Date: 09/11/2018
 * Time: 17:58
 */

namespace QHO\Hello\Block;
class Add extends \Magento\Framework\View\Element\Template
{
    protected function _prepareLayout()
    {
        $this->assign("data", "Welcome to Add Action");
        $this->assign("url", $this->getBaseUrl());
        $this->setData("abc", "Gia tri ABC");
        return parent::_prepareLayout(); // TODO: Change the autogenerated stub
    }

    public function getDemo()
    {
        $arr = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];
        return $arr;
    }
}