<?php
/**
 * Created by PhpStorm.
 * User: thangnguyen
 * Date: 09/11/2018
 * Time: 17:21
 */

namespace QHO\Hello\Block;

use Magento\Framework\Registry;
use Magento\Framework\View\Element\Template;

class Hello extends \Magento\Framework\View\Element\Template
{
    protected $_coreRegistry;
    protected $_objectManager;

    public function __construct(Template\Context $context, Registry $coreRegistry, array $data = [])
    {
        $this->_coreRegistry = $coreRegistry;
        parent::__construct($context, $data);
    }

    protected function _prepareLayout()
    {
        $slogan = $this->_coreRegistry->registry("qho");
        $this->assign("slogan", $slogan);
        return parent::_prepareLayout(); // TODO: Change the autogenerated stub
    }
}