<?php
/**
 * Created by PhpStorm.
 * User: thangnguyen
 * Date: 09/11/2018
 * Time: 15:55
 */
namespace QHO\Schema\Model;

class DataExample extends \Magento\Framework\Model\AbstractModel{
    /**
     * construct
     */
    public function _construct()
    {
        $this->_init("QHO\Schema\Model\ResourceModel\DataExample");
        parent::_construct(); // TODO: Change the autogenerated stub
    }
}